site_url: https://malinparker.netlify.app/
logo_url: https://malinparker.netlify.app/icon.png

publish_mode: editorial_workflow
backend:
  name: git-gateway
  branch: master
  squash_merges: true

media_folder: static/img
public_folder: /img

# ? Docs: https://www.netlifycms.org/docs/configuration-options/#collections
collections:
  - name: 'site'
    label: 'Site settings'
    files:
      - label: 'General Setup & Info'
        name: 'info'
        file: 'assets/content/site/info.json'
        format: 'json'
        editor:
          preview: false
        fields:
          - { label: Site Name, name: sitename, widget: string, hint: 'This is used for the site title' }
          - {
              label: Site Description,
              name: sitedescription,
              widget: string,
              hint: 'This is used as descriptive text for links that link to this site',
            }
          - {
              label: Site Language,
              name: sitelang,
              widget: string,
              pattern: ['^[a-z]{2}([-])?([A-Za-z]{2})?$', 'Must match "xx" or "xx-XX" syntax (ex. "en" or "sv-SE")'],
            }
          - { label: 'Résumé URL', name: 'resumeUrl', widget: 'image', required: false, allow_multiple: false }
          # - { label: Site Email, name: siteemail, widget: string, required: false }
  - name: 'case'
    label: 'Case Studies'
    label_singular: 'Case Study'
    folder: 'assets/content/cases'
    create: true
    format: 'json'
    identifier_field: slug
    slug: '{{slug}}'
    preview_path: 'cases/{{slug}}'
    fields:
      - {
          label: Order,
          description: 'Put the number in which order you want the design to have and match it according to the others (tip: set the numbers in orders of 10, so that you can fit another one between someday)',
          name: order,
          widget: number,
          min: 1,
          max: 10000,
          value_type: int,
          required: true,
          default: 100
        }
      - { label: 'URL slug', name: 'slug', widget: 'string', required: true, pattern: ['[a-z-]', 'Must be small letters and dashes'], hint: 'What should the url be? /cases/SLUG_HERE' }
      - { label: 'Selected work', name: 'selected', widget: 'boolean', required: false, hint: 'Should it appear on the start page?' }
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Excerpt', name: 'excerpt', widget: 'string', required: false }
      - {
          label: 'Cover Image',
          name: 'cover',
          widget: 'object',
          required: false,
          fields: [
            { label: 'Cover Image Source', name: 'src', widget: 'image', required: false, allow_multiple: false },
            { label: 'Cover Image Alt', name: 'alt', widget: 'string', required: false },
            {
              label: 'Cover Image Placeholder Height',
              name: 'height',
              description: 'The estimated height of the picture that will be used for the placeholder before the image has loaded (in pixels)',
              widget: number,
              min: 100,
              max: 1000,
              value_type: int,
              required: false
            },
          ]
        }
      - { label: 'Content', name: 'body', widget: 'markdown', minimal: true, required: false }
      - {
          label: 'Metadata',
          name: 'meta',
          widget: 'object',
          required: false,
          fields: [
            {
              label: 'Visible Steps',
              name: 'visibleSteps',
              widget: 'select',
              multiple: true,
              required: false,
              options: [
                { label: 'Research', value: 1 },
                { label: 'Empathize', value: 2 },
                { label: 'Ideate', value: 3 },
                { label: 'Prototype', value: 4 },
                { label: 'Test', value: 5 },
              ]
            },
            { label: 'Duration', name: 'duration', widget: 'string', hint: 'eg. "5 days"', required: false },
            { label: 'Methods', name: 'methods', widget: 'string', required: false },
            { label: 'Tools', name: 'tools', widget: 'string', required: false },
            { label: 'Role', name: 'role', widget: 'string', required: false },
            { label: 'Worked With', name: 'workedWith', widget: 'string', required: false },
          ]
        }
      - { label: 'Context', name: 'context', widget: 'markdown', minimal: true, required: false }
      - {
          label: "Steps",
          name: "steps",
          widget: "list",
          summary: '{{fields.title}}',
          fields: [
            {
              label: 'Step type',
              name: 'type',
              widget: 'select',
              multiple: false,
              required: true,
              options: [
                { label: 'Empathize', value: 1 },
                { label: 'Define', value: 2 },
                { label: 'Ideate', value: 3 },
                { label: 'Prototype', value: 4 },
                { label: 'Test', value: 5 },
              ]
            },
            { label: Title, name: title, widget: string, required: true },
            { label: 'Content', name: 'body', widget: 'markdown', minimal: true, required: false },
            { label: 'Larger images', name: 'largerImages', widget: 'boolean', required: false, hint: 'Should the images take up a larger area than the text?' },
            {
              label: 'Images',
              name: 'images',
              widget: 'list',
              required: false,
              collapsed: true,
              summary: '{{fields.image.src}} - {{fields.image.alt}}',
              field: {
                label: 'Image',
                name: 'image',
                widget: 'object',
                required: false,
                fields: [
                  { label: 'Image Source', name: 'src', widget: 'image', required: false, allow_multiple: false },
                  { label: 'Image Alt', name: 'alt', widget: 'string', required: false },
                ]
              },
            }
          ],
        }
      - {
          label: 'Final Product',
          name: 'final',
          widget: 'list',
          required: false,
          summary: '{{fields.image.src}} - {{fields.image.alt}}',
          fields: [
            { label: 'Image Source', name: 'src', widget: 'image', required: false, allow_multiple: false },
            { label: 'Image Alt', name: 'alt', widget: 'string', required: false },
            { label: 'Image Text', name: 'body', widget: 'markdown', minimal: true, required: false },
          ]
        }
      - { label: 'Retrospective', name: 'retrospective', widget: 'markdown', minimal: true, required: false }
  - name: 'design'
    label: 'Graphic Designs'
    label_singular: 'Graphic Design'
    folder: 'assets/content/designs'
    create: true
    format: 'json'
    identifier_field: slug
    slug: '{{slug}}'
    preview_path: 'designs/{{slug}}'
    fields:
      - {
          label: Order,
          description: 'Put the number in which order you want the design to have and match it according to the others (tip: set the numbers in orders of 10, so that you can fit another one between someday)',
          name: order,
          widget: number,
          min: 1,
          max: 10000,
          value_type: int,
          required: true,
          default: 100
        }
      - { label: 'URL slug', name: 'slug', widget: 'string', required: true, pattern: ['[a-z-]', 'Must be small letters and dashes'], hint: 'What should the url be? /designs/SLUG_HERE' }
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Content', name: 'body', widget: 'markdown', minimal: true, required: false }
      - {
          label: 'Cover Image',
          name: 'cover',
          widget: 'object',
          required: false,
          fields: [
            { label: 'Cover Image Source', name: 'src', widget: 'image', required: false, allow_multiple: false },
            { label: 'Cover Image Alt', name: 'alt', widget: 'string', required: false },
            {
              label: 'Cover Image Placeholder Height',
              name: 'height',
              description: 'The estimated height of the picture that will be used for the placeholder before the image has loaded (in pixels)',
              widget: number,
              min: 100,
              max: 1000,
              value_type: int,
              required: false
            },
          ]
        }
      - {
          label: 'Additional Images',
          name: 'images',
          widget: 'list',
          required: false,
          collapsed: true,
          summary: '{{fields.image.src}} - {{fields.image.alt}}',
          fields: [
            { label: 'Image Source', name: 'src', widget: 'image', required: false, allow_multiple: false },
            { label: 'Image Alt', name: 'alt', widget: 'string', required: false },
          ]
        }
